tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "curl"
brew "git"
brew "bat"
brew "exa"
brew "tree"
brew "make"
brew "zplug"
brew "zsh-git-prompt"
brew "zsh-completion"
brew "yarn"
brew "python"
brew "pipenv"
brew "pyenv"
brew "docker"
brew "mysql@5.7", restart_service: true

cask "tabby"
cask "visual-studio-code"
cask "alfred"
cask "clipy"
cask "alt-tab"
cask "slack"
cask "zoomus"
cask "fork"
cask "deepl"
cask "postman"
cask "notion"
cask "chromedriver"
