tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "curl"
brew "git"
brew "bat"
brew "exa"
brew "tree"
brew "zplug"
brew "zsh-git-prompt"
brew "zsh-completion"
brew "yarn"
brew "python"
brew "pipenv"
brew "pyenv"
brew "mysql@8.0", restart_service: true

cask "visual-studio-code"
cask "alfred"
cask "clipy"
cask "alt-tab"
cask "slack"
cask "zoomus"
cask "postman"
cask "chromedriver"
